name: HTML5 Validator
on: [pull_request]
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: Cyb3r-Jak3/html5validator-action@v0.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
